### ISSUE TITLE
Resume/Retry at 'attempt failed because the connected party did not properly respond'

### ISSUE THREAD

**Issue by sabatale** [sujitmandal/url-into-images#1]
Great piece of code! Is there a way to resume, retry or skip error whenever a timeout happens? At the moment, you just have to adjust your CSV to start where it crashed. Since the naming convention restarts at image0 and there is no "do not replace" option, it makes it tricky to deal with large datasets.

`<urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>`

**Comment by sujitmandal** [comment]
Thanks for your feedback i will look at into it. but can you provide me the input link [ IMAGE_PATH ]  so that i can solve the problem  because i don't have that kind of link right now....
